Alias /umla-api /var/www/umla-backend/public

<Directory /var/www/umla-backend/public>
    Options Indexes FollowSymLinks
    AllowOverride All
    DirectoryIndex index.php
    Require all granted
</Directory>